"""Project-centric, multi-role, multi-model platform extensions for OxyGent."""

from .artifacts import (
    ArchitectureDecision,
    ArchitectureDecisionContent,
    Artifact,
    ArtifactBase,
    ArtifactType,
    InMemoryArtifactStore,
    RequirementSpec,
    RequirementSpecContent,
    ReviewFinding,
    ReviewReport,
    ReviewReportContent,
    TaskGraph,
    TaskGraphContent,
    TaskNode,
    ValidationStatus,
)
from .credentials import (
    CredentialResolver,
    EnvironmentCredentialResolver,
    MappingCredentialResolver,
)
from .profiles import (
    AgentProfile,
    HealthStatus,
    ModelProfile,
    ProviderProfile,
    ProviderType,
    RoleDefinition,
    RoleModelPolicy,
    RoutingMode,
    ToolPolicy,
    default_role_definitions,
)
from .provider_adapters import (
    GeminiAdapter,
    HealthResult,
    ModelEvent,
    ModelProviderAdapter,
    ModelRequest,
    ModelResponse,
    OllamaAdapter,
    OpenAICompatibleAdapter,
    ProviderAdapterRegistry,
    ProviderCallError,
    default_provider_adapters,
)
from .registries import (
    AgentProfileRegistry,
    ModelRegistry,
    ProviderRegistry,
    RegistryError,
    RoleModelPolicyRegistry,
    RoleRegistry,
    ToolPolicyRegistry,
)
from .routing import (
    ModelRouteDecision,
    ModelRouter,
    ModelRoutingEngine,
    ModelRoutingError,
    RoutingContext,
)
from .tracing import ExecutionTrace, InMemoryExecutionTraceStore, RouteDecisionTrace
from .usage import InMemoryModelUsageStore, InvocationStatus, ModelUsage
from .workflow import BasicRoleWorkflow

__all__ = [
    "AgentProfile",
    "AgentProfileRegistry",
    "ArchitectureDecision",
    "ArchitectureDecisionContent",
    "Artifact",
    "ArtifactBase",
    "ArtifactType",
    "BasicRoleWorkflow",
    "CredentialResolver",
    "EnvironmentCredentialResolver",
    "ExecutionTrace",
    "GeminiAdapter",
    "HealthResult",
    "HealthStatus",
    "InMemoryArtifactStore",
    "InMemoryExecutionTraceStore",
    "InMemoryModelUsageStore",
    "InvocationStatus",
    "MappingCredentialResolver",
    "ModelEvent",
    "ModelProfile",
    "ModelProviderAdapter",
    "ModelRegistry",
    "ModelRequest",
    "ModelResponse",
    "ModelRouteDecision",
    "ModelRouter",
    "ModelRoutingEngine",
    "ModelRoutingError",
    "ModelUsage",
    "OllamaAdapter",
    "OpenAICompatibleAdapter",
    "ProviderAdapterRegistry",
    "ProviderCallError",
    "ProviderProfile",
    "ProviderRegistry",
    "ProviderType",
    "RegistryError",
    "RequirementSpec",
    "RequirementSpecContent",
    "ReviewFinding",
    "ReviewReport",
    "ReviewReportContent",
    "RoleDefinition",
    "RoleModelPolicy",
    "RoleModelPolicyRegistry",
    "RoleRegistry",
    "RouteDecisionTrace",
    "RoutingContext",
    "RoutingMode",
    "TaskGraph",
    "TaskGraphContent",
    "TaskNode",
    "ToolPolicy",
    "ToolPolicyRegistry",
    "ValidationStatus",
    "default_provider_adapters",
    "default_role_definitions",
]
